### PR TITLE
csh-material-login v2

### PR DESCRIPTION
**Pull request by stevenmirabito**
Brings a much-needed refresh to the login theme.

- Revamps build system to remove Gulp in favor of [Neutrino](https://neutrinojs.org) + a handful of Node scripts
- Fresh slate of up-to-date dependencies
- React code has been largely rewritten to remove Redux, migrate to TypeScript, and leverage hooks
- Update templates for Keycloak 11.0.2
- Upgrade to `csh-material-bootstrap@4.5.2`
- Automatic deployments to S3 via Drone CI
- Various theme fixes

## Screenshots
Screen Shot 2020-09-12 at 6 35 38 PM
Screen Shot 2020-09-12 at 4 23 14 PM
Screen Shot 2020-09-12 at 5 42 43 PM
Screen Shot 2020-09-12 at 6 35 47 PM

### CODE REVIEW

**Comment by Lontronix** [comment]
Kind of wish the 2FA glyph was aligned with the code but other than that I think this looks great!

**Comment by mbillow** [comment]
I really wish this was broken into to MRs for the dependency/build updates and then the actual theme changes. I scrolled through a bunch of random JS build ecosystem garbage before I got to anything related to the theme. 🧐

This is a good foundation for the time being. I’d rather this concern it be about styling nitpicking, since MRs can be made once this gets merged to address and discuss stuff like that.

Personally, I am fine with this as is.

**Comment by stevenmirabito** [comment]
@mbillow I would normally prefer smaller PRs as well; the problem with that is the changes are interdependent: the build system won't build the old code and the new code won't build on the old build system. For the most part, the build system changes are contained in the first commit with only minor tweaks in the subsequent commits for the meat of the code changes.

My intention with this was to bring things up-to-date so we had a platform that could continue to be iterated on.

**Review by devinmatte — APPROVED** [review]
There is no way I could ever reasonably review this PR. However, I trust that you've done the minimal amount of testing, and that it's likely well engineered.

**Comment by devinmatte** [comment]
I want to wait until we have bumped up to keycloak 11 before merging this. That should be a trivial change

**Review by mxmeinhold — APPROVED** [review]
I pretended to read most of this. This looks nice. Thanks @stevenmirabito!
:ship: :it:

**Pull request merged**
