### PR TITLE
Three New Themes

### PR DESCRIPTION
**Pull request by devinmatte**
I decided to mess around learning how to make Themes for the Login. Since we currently only have one acceptable theme (Original Photo), I figured we needed some more options. 
So I added 3 more so that we now have *One acceptable Option*, plus now 3 extra ones for fun!

Bonney's Theme
----------------------

RIT Orange
----------------

Hacking the Mainframe
-------------------------------

### CODE REVIEW

**Comment by liam-middlebrook** [comment]
For maximum hacking I think the terminal should be an animated image.

Also it would be great if we didn't use potentially copyrighted content like that.

**Comment by devinmatte** [comment]
If you're worried about copyright law, this would be protected under both Fair Use (All four factors). I swapped out the image for one that cannot be legally copyrighted (due to the distinguishing letters being what makes the copyright valid). It's also now animated!

**Comment by stevenmirabito** [comment]
Looks good, we can merge this once I fix #3

**Review by stevenmirabito — APPROVED** [review]
:shipit:

**Pull request merged**
